### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by 4ss3g4f** [codenoid/file.io#7]
```
panic: empty DATABASE || DATABASE_TYPE (redis/badger) env

goroutine 1 [running]: 

 main.main() 

 github.com/codenoid/file.io/fileio.go:28 +0x3b2
```
We've add env DATABASE but still error, thank you

**Comment by 4ss3g4f** [comment]
![image](https://user-images.githubusercontent.com/22811935/89375553-1cc3c380-d718-11ea-93cc-9d74911313d4.png)

```
version: '3.7'

networks:
  bridge:
    external: true

services:
  fileio:
    image: codenoid/file.io-clone:latest
    deploy:
      restart_policy:                                                   
        condition: on-failure                                           
        delay: 5s                                                       
        max_attempts: 3                                                 
        window: 120s
    networks:
      - bridge
    depends_on:
      - 10.100.80.3
    environment:
      DATABASE_TYPE: "redis"
      DATABASE: "redis://10.100.80.3:6379/1"
    ports:
      - "8070:8080"
```
